In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
# Write your code for importing the csv file here
movies = pd.read_csv("Movie+Assignment+Data.csv") 
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here
movies.isnull().sum(axis=0)

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [7]:
# Write your code for column-wise null percentages here
(movies.isnull().sum(axis=0)/len(movies)*100).round(2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [8]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies1=movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords'],axis=1)
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,629,6.0,English,NaN,2013.0,7.7,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,73839,359.0,English,NaN,NaN,7.5,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,38,3.0,English,1400.0,2013.0,6.3,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,1255,9.0,English,NaN,2012.0,6.3,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [9]:
# Write your code for dropping the rows here
movies1.isnull().sum(axis=1)/len(movies1)>5
movies1=movies1[~np.isnan(movies1['gross'])]
movies1=movies1[~np.isnan(movies1['budget'])]
movies1.isnull().sum(axis=0)/len(movies1.index)

director_name             0.000000
num_critic_for_reviews    0.000257
gross                     0.000000
genres                    0.000000
actor_1_name              0.000771
movie_title               0.000000
num_voted_users           0.000000
num_user_for_reviews      0.000000
language                  0.000771
budget                    0.000000
title_year                0.000000
imdb_score                0.000000
movie_facebook_likes      0.000000
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [10]:
# Write your code for dropping the rows here
movies1=movies1[movies1.isnull().sum(axis=1)<=5]
(movies1.isnull().sum(axis=0)/len(movies1)*100).round(2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [11]:
# Write your code for filling the NaN values in the 'language' column here
movies1["language"].fillna("English", inplace = True) 
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [12]:
# Write your code for checking number of retained rows here
row=len(movies1)
print(row)
print(round(row/len(movies)*100,2))

3891
77.16

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [13]:
# Write your code for unit conversion here
movies1[['budget','gross']]=movies1[['budget','gross']].apply(lambda x:x/1000000)
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [14]:
# Write your code for creating the profit column here
movies1['profit']=movies1['gross']-movies1['budget']
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000,-190.641321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000,0.417760
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74,0.063071
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0,2.033920
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413,-0.004416
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456,0.084122

In [15]:
# Write your code for sorting the dataframe here
movies1=movies1.sort_values('profit', ascending=False)
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [16]:
# Write your code to get the top 10 profiting movies here
top10 = movies1.head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [17]:
# Write your code for dropping duplicate values here
movies1.drop_duplicates(keep='first',inplace=True)
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [18]:
# Write code for repeating subtask 2 here
top10 = movies1.head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [19]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
movies2=movies1.where(movies1['num_voted_users']>25000)
movies2.dropna(how='all')
IMDb_Top_250=movies2.nlargest(250,['imdb_score'])
IMDb_Top_250.insert(0,'Rank',range(1,251))
IMDb_Top_250

,Rank,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,1,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764.0,4144.0,English,25.0,1994.0,9.3,108000.0,3.341469
3466,2,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770.0,2238.0,English,6.0,1972.0,9.2,43000.0,128.821952
66,3,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169.0,4667.0,English,185.0,2008.0,9.0,37000.0,348.316061
2837,4,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926.0,650.0,English,13.0,1974.0,9.0,14000.0,44.300000
339,5,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718.0,3189.0,English,94.0,2003.0,8.9,16000.0,283.019252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,246,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149.0,316.0,Japanese,19.0,2006.0,7.9,5000.0,-5.246069
1813,247,Philip Kaufman,80.0,21.500000,Adventure|Drama|History,Dennis Quaid,The Right Stuff,45271.0,170.0,English,27.0,1983.0,7.9,0.0,-5.500000
3264,248,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382.0,190.0,French,8.9,2012.0,7.9,33000.0,-8.674623
2449,249,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416.0,420.0,English,18.0,1994.0,7.9,0.0,-12.112543
1993,250,Roger Donaldson,126.0,5.128124,Biography|Drama|Sport,Anthony Hopkins,The World's Fastest Indian,44198.0,251.0,English,25.0,2005.0,7.9,11000.0,-19.871876

In [20]:
# Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDb_Top_250.loc[(IMDb_Top_250.language!='English'),:]
Top_Foreign_Lang_Film

,Rank,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
4498,8,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509.0,780.0,Italian,1.200000,1966.0,8.9,20000.0,4.900000
4029,19,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200.0,749.0,Portuguese,3.300000,2002.0,8.7,28000.0,4.263397
4747,20,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012.0,596.0,Japanese,2.000000,1954.0,8.7,11000.0,-1.730939
2373,28,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971.0,902.0,Japanese,19.000000,2001.0,8.6,28000.0,-8.950114
4259,44,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379.0,407.0,German,2.000000,2006.0,8.5,39000.0,9.284657
4921,45,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882.0,130.0,Persian,0.180000,1997.0,8.5,0.0,0.745402
4659,51,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812.0,264.0,Persian,0.500000,2011.0,8.4,48000.0,6.598492
4105,54,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181.0,809.0,Korean,3.000000,2003.0,8.4,43000.0,-0.818710
2970,56,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203.0,426.0,German,14.000000,1981.0,8.4,11000.0,-2.566866
1329,58,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756.0,410.0,Telugu,18.026148,2015.0,8.4,21000.0,-11.528148
1298,60,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,Amélie,534262.0,1314.0,French,77.000000,2001.0,8.4,39000.0,-43.798339
2323,61,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552.0,570.0,Japanese,2400.000000,1997.0,8.4,11000.0,-2397.701809
4033,81,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155.0,249.0,Danish,3.800000,2012.0,8.3,60000.0,-3.189032
2734,82,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841.0,413.0,German,6.000000,1927.0,8.3,12000.0,-5.973565
2829,83,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354.0,564.0,German,13.500000,2004.0,8.3,14000.0,-7.998060
2551,93,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234.0,1083.0,Spanish,13.500000,2006.0,8.2,27000.0,24.123143
4000,94,Juan José Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831.0,231.0,Spanish,2.000000,2009.0,8.2,33000.0,18.167424
3550,102,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429.0,156.0,French,6.800000,2010.0,8.2,37000.0,0.057096
2047,107,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091.0,330.0,Japanese,24.000000,2004.0,8.2,13000.0,-19.289545
4267,144,Alejandro G. Iñárritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551.0,361.0,Spanish,2.000000,2000.0,8.1,11000.0,3.383834
4461,146,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951.0,258.0,Danish,1.300000,1998.0,8.1,5000.0,0.347780
3553,148,José Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644.0,107.0,Portuguese,4.000000,2007.0,8.1,11000.0,-3.991940
2830,149,Alejandro Amenábar,157.0,2.086345,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556.0,140.0,Spanish,10.000000,2004.0,8.1,0.0,-7.913655
2914,151,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943.0,224.0,Korean,12.800000,2004.0,8.1,0.0,-11.689814
3423,152,Katsuhiro Ôtomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160.0,430.0,Japanese,1100.000000,1988.0,8.1,0.0,-1099.560838
4897,187,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566.0,235.0,Italian,0.200000,1964.0,8.0,0.0,3.300000
4144,189,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951.0,257.0,Portuguese,2.900000,1998.0,8.0,0.0,2.695428
4284,191,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107.0,156.0,Hebrew,1.500000,2008.0,8.0,0.0,0.783276
3456,193,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194.0,158.0,French,7.300000,2007.0,8.0,14000.0,-2.856597
3344,199,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759.0,235.0,Hindi,12.000000,2010.0,8.0,27000.0,-7.981305
2605,214,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740.0,1641.0,Mandarin,15.000000,2000.0,7.9,0.0,113.067808
4640,241,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763.0,172.0,Romanian,0.590000,2007.0,7.9,14000.0,0.595783
4415,243,Fabián Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215.0,125.0,Spanish,1.500000,2000.0,7.9,0.0,-0.278739
3677,244,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151.0,110.0,French,5.500000,2004.0,7.9,0.0,-1.870242
3510,245,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449.0,119.0,Hindi,7.000000,2004.0,7.9,2000.0,-4.078262
2863,246,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149.0,316.0,Japanese,19.000000,2006.0,7.9,5000.0,-5.246069
3264,248,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382.0,190.0,French,8.900000,2012.0,7.9,33000.0,-8.674623

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [21]:
# Write your code for extracting the top 10 directors here
movies3=movies2.groupby('director_name').agg({'imdb_score':'mean'})
top10director=movies3.sort_values('imdb_score',ascending=False).head(10)
top10director

                   imdb_score
director_name
Akira Kurosawa       8.700000
Charles Chaplin      8.600000
Tony Kaye            8.600000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [22]:
# Write your code for extracting the first two genres of each movie here
movies1['genre_1']=movies1['genres'].apply(lambda x: x.split("|")[0])
movies1['genre_2']=movies1['genres'].apply(lambda x: x.split("|")[1] if len(x.split("|"))>1 else x)
movies1

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847,Action,Adventure
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271,Action,Adventure
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302,Drama,Romance
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665,Action,Adventure
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459,Family,Sci-Fi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510,Action,Adventure
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,Adventure,Animation
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112,Drama,Romance
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333,Crime,Drama
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588,Comedy,Drama

In [31]:
# Write your code for grouping the dataframe here
movies_by_segment = movies1.groupby(['genre_1','genre_2'])

In [32]:
# Write your code for getting the 5 most popular combo of genres here
PopGenre = movies_by_segment['gross'].mean().sort_values(ascending=False).head()
PopGenre

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [25]:
# Write your code for creating three new dataframes here

# Include all movies in which Meryl_Streep is the lead
Meryl_Streep = movies1.where(movies1['actor_1_name']=='Meryl Streep')
Meryl_Streep.dropna(how='all',inplace=True)
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178.0,631.0,English,35.0,2006.0,6.8,0.0,89.732962,Comedy,Drama
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339.0,200.0,English,31.0,1985.0,7.2,0.0,56.100000,Biography,Drama
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264.0,277.0,English,40.0,2009.0,7.0,13000.0,54.125426,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258.0,178.0,English,30.0,2012.0,6.3,0.0,33.536011,Comedy,Drama
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860.0,214.0,English,85.0,2009.0,6.6,0.0,27.703470,Comedy,Drama
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327.0,350.0,English,13.0,2011.0,6.4,18000.0,16.959436,Biography,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123.0,660.0,English,25.0,2002.0,7.6,0.0,16.597830,Drama,Romance
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655.0,280.0,English,10.0,2006.0,6.8,683.0,10.338609,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544.0,69.0,English,45.0,1994.0,6.3,0.0,1.815748,Action,Adventure
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283.0,112.0,English,30.0,1998.0,7.0,592.0,-6.790560,Drama,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170.0,298.0,English,35.0,2007.0,6.2,0.0,-20.001930,Drama,Thriller

In [26]:
# Include all movies in which Leo_Caprio is the lead
Leo_Caprio = movies.where(movies['actor_1_name']=='Leonardo DiCaprio')
Leo_Caprio.dropna(how='all',inplace=True)
Leo_Caprio

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000.0
50,Color,Baz Luhrmann,490.0,143.0,1000.0,77.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,753.0,English,Australia,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000.0
97,Color,Christopher Nolan,642.0,148.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,...,2803.0,English,USA,PG-13,160000000.0,2010.0,27000.0,8.8,2.35,175000.0
179,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,1188.0,English,USA,R,135000000.0,2015.0,27000.0,8.1,2.35,190000.0
257,Black and White,Martin Scorsese,267.0,170.0,17000.0,827.0,Adam Scott,29000.0,102608827.0,Biography|Drama,...,799.0,English,USA,PG-13,110000000.0,2004.0,3000.0,7.5,2.35,0.0
296,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,2.35,199000.0
307,Color,Edward Zwick,166.0,143.0,380.0,452.0,Djimon Hounsou,29000.0,57366262.0,Adventure|Drama|Thriller,...,657.0,English,Germany,R,100000000.0,2006.0,3000.0,8.0,2.35,14000.0
308,Color,Martin Scorsese,606.0,240.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,...,1138.0,English,USA,R,100000000.0,2013.0,11000.0,8.2,2.35,138000.0
326,Color,Martin Scorsese,233.0,216.0,17000.0,1000.0,Liam Neeson,29000.0,77679638.0,Crime|Drama,...,1166.0,English,USA,R,100000000.0,2002.0,14000.0,7.5,2.35,0.0
361,Color,Martin Scorsese,352.0,151.0,17000.0,1000.0,Matt Damon,29000.0,132373442.0,Crime|Drama|Thriller,...,2054.0,English,USA,R,90000000.0,2006.0,13000.0,8.5,2.35,29000.0
452,Color,Martin Scorsese,490.0,138.0,17000.0,163.0,Joseph Sikora,29000.0,127968405.0,Mystery|Thriller,...,964.0,English,USA,R,80000000.0,2010.0,223.0,8.1,2.35,53000.0
641,Color,Ridley Scott,238.0,128.0,0.0,135.0,Simon McBurney,29000.0,39380442.0,Action|Drama|Thriller,...,263.0,English,USA,R,70000000.0,2008.0,149.0,7.1,2.35,0.0
911,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,667.0,English,USA,PG-13,52000000.0,2002.0,15000.0,8.0,1.85,15000.0
990,Color,Danny Boyle,118.0,119.0,0.0,39.0,Virginie Ledoyen,29000.0,39778599.0,Adventure|Drama|Thriller,...,548.0,English,USA,R,50000000.0,2000.0,414.0,6.6,2.35,0.0
1114,Color,Sam Mendes,323.0,119.0,0.0,10000.0,Kate Winslet,29000.0,22877808.0,Drama|Romance,...,414.0,English,USA,R,35000000.0,2008.0,14000.0,7.3,2.35,0.0
1422,Color,Randall Wallace,83.0,132.0,130.0,80.0,Anne Parillaud,29000.0,56876365.0,Action|Adventure,...,244.0,English,USA,PG-13,35000000.0,1998.0,130.0,6.4,1.85,0.0
1453,Color,Clint Eastwood,392.0,137.0,16000.0,363.0,Naomi Watts,29000.0,37304950.0,Biography|Crime|Drama,...,279.0,English,USA,R,35000000.0,2011.0,6000.0,6.6,2.35,16000.0
1560,Black and White,Sam Raimi,63.0,107.0,0.0,159.0,Pat Hingle,29000.0,18636537.0,Action|Thriller|Western,...,216.0,English,Japan,R,32000000.0,1995.0,165.0,6.4,1.85,0.0
2067,Color,Jerry Zaks,45.0,98.0,4.0,11000.0,Robert De Niro,29000.0,12782508.0,Drama,...,71.0,English,USA,PG-13,23000000.0,1996.0,22000.0,6.7,1.85,1000.0
2757,Color,Baz Luhrmann,106.0,120.0,1000.0,954.0,Harold Perrineau,29000.0,46338728.0,Drama|Romance,...,506.0,English,USA,PG-13,14500000.0,1996.0,1000.0,6.8,2.35,10000.0
3476,Color,Baz Luhrmann,490.0,143.0,1000.0,76.0,Elizabeth Debicki,29000.0,144812796.0,Drama|Romance,...,753.0,English,Australia,PG-13,105000000.0,2013.0,509.0,7.3,2.35,115000.0

In [27]:
# Include all movies in which Brad_Pitt is the lead
Brad_Pitt = movies.where(movies['actor_1_name']=='Brad Pitt')
Brad_Pitt.dropna(how='all',inplace=True)
Brad_Pitt

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
101,Color,David Fincher,362.0,166.0,21000.0,919.0,Jason Flemyng,11000.0,127490802.0,Drama|Fantasy|Romance,...,822.0,English,USA,PG-13,150000000.0,2008.0,1000.0,7.8,2.35,23000.0
147,Color,Wolfgang Petersen,220.0,196.0,249.0,844.0,Orlando Bloom,11000.0,133228348.0,Adventure,...,1694.0,English,USA,R,175000000.0,2004.0,5000.0,7.2,2.35,0.0
254,Color,Steven Soderbergh,198.0,125.0,0.0,350.0,Julia Roberts,11000.0,125531634.0,Crime|Thriller,...,627.0,English,USA,PG-13,110000000.0,2004.0,8000.0,6.4,2.35,0.0
255,Color,Doug Liman,233.0,126.0,218.0,322.0,Angelina Jolie Pitt,11000.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,...,798.0,English,USA,PG-13,120000000.0,2005.0,11000.0,6.5,2.35,0.0
382,Color,Tony Scott,142.0,114.0,12000.0,307.0,Stephen Dillane,11000.0,26871.0,Action|Crime|Thriller,...,361.0,English,Germany,R,92000000.0,2001.0,577.0,7.0,2.35,0.0
400,Color,Steven Soderbergh,186.0,116.0,0.0,471.0,Bernie Mac,11000.0,183405771.0,Crime|Thriller,...,845.0,English,USA,PG-13,85000000.0,2001.0,1000.0,7.8,2.35,0.0
470,Color,David Ayer,406.0,134.0,452.0,697.0,Logan Lerman,11000.0,85707116.0,Action|Drama|War,...,701.0,English,USA,R,68000000.0,2014.0,8000.0,7.6,2.35,82000.0
611,Color,Jean-Jacques Annaud,76.0,136.0,218.0,400.0,Mako,11000.0,37901509.0,Adventure|Biography|Drama|History|War,...,119.0,English,USA,PG-13,70000000.0,1997.0,691.0,7.0,2.35,0.0
683,Color,David Fincher,315.0,151.0,21000.0,637.0,Meat Loaf,11000.0,37023395.0,Drama,...,2968.0,English,USA,R,63000000.0,1999.0,783.0,8.8,2.35,48000.0
792,Color,Patrick Gilmore,98.0,85.0,0.0,82.0,Adriano Giannini,11000.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,...,91.0,English,USA,PG,60000000.0,2003.0,102.0,6.7,1.66,880.0
940,Color,Neil Jordan,120.0,123.0,277.0,4000.0,Tom Cruise,11000.0,105264608.0,Drama|Fantasy|Horror,...,406.0,English,USA,R,60000000.0,1994.0,10000.0,7.6,1.85,11000.0
1490,Color,Terrence Malick,584.0,139.0,0.0,687.0,Tye Sheridan,11000.0,13303319.0,Drama|Fantasy,...,975.0,English,USA,PG-13,32000000.0,2011.0,1000.0,6.7,1.85,39000.0
1722,Color,Andrew Dominik,273.0,160.0,181.0,820.0,Jeremy Renner,11000.0,3904982.0,Biography|Crime|Drama|History|Western,...,415.0,English,USA,R,30000000.0,2007.0,10000.0,7.5,2.35,0.0
2204,Color,Alejandro G. Iñárritu,285.0,143.0,0.0,51.0,Harriet Walter,11000.0,34300771.0,Drama,...,908.0,English,France,R,25000000.0,2006.0,119.0,7.5,1.85,0.0
2333,Color,Angelina Jolie Pitt,131.0,122.0,11000.0,188.0,Angelina Jolie Pitt,11000.0,531009.0,Drama|Romance,...,61.0,English,USA,R,10000000.0,2015.0,11000.0,5.3,2.35,0.0
2682,Color,Andrew Dominik,414.0,97.0,181.0,748.0,Sam Shepard,11000.0,14938570.0,Crime|Thriller,...,369.0,English,USA,R,15000000.0,2012.0,820.0,6.2,2.35,20000.0
2898,Color,Tony Scott,122.0,121.0,12000.0,975.0,Gary Oldman,11000.0,12281500.0,Action|Crime|Drama|Romance|Thriller,...,460.0,English,USA,R,13000000.0,1993.0,10000.0,8.0,2.35,15000.0
4749,Black and White,Tom DiCillo,10.0,97.0,32.0,329.0,Tina Louise,11000.0,NaN,Comedy|Music|Romance,...,24.0,English,Switzerland,R,500000.0,1991.0,422.0,5.8,1.85,344.0

In [28]:
# Write your code for combining the three dataframes here
Combined=pd.concat([Meryl_Streep,Leo_Caprio,Brad_Pitt])
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,...,actor_1_facebook_likes,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,country,content_rating,actor_2_facebook_likes,aspect_ratio
1408,David Frankel,208.0,1.247330e+02,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178.0,631.0,English,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1575,Sydney Pollack,66.0,8.710000e+01,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339.0,200.0,English,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1204,Nora Ephron,252.0,9.412543e+01,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264.0,277.0,English,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1618,David Frankel,234.0,6.353601e+01,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258.0,178.0,English,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,Nancy Meyers,187.0,1.127035e+02,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860.0,214.0,English,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2781,Phyllida Lloyd,331.0,2.995944e+01,Biography|Drama|History,Meryl Streep,The Iron Lady,82327.0,350.0,English,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1925,Stephen Daldry,174.0,4.159783e+01,Drama|Romance,Meryl Streep,The Hours,102123.0,660.0,English,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3135,Robert Altman,211.0,2.033861e+01,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655.0,280.0,English,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106,Curtis Hanson,42.0,4.681575e+01,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544.0,69.0,English,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1674,Carl Franklin,64.0,2.320944e+01,Drama,Meryl Streep,One True Thing,9283.0,112.0,English,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,Robert Redford,227.0,1.499807e+01,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170.0,298.0,English,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,James Cameron,315.0,6.586723e+08,Drama|Romance,Leonardo DiCaprio,Titanic,793059.0,2528.0,English,200000000.0,...,29000.0,45223.0,Gloria Stuart,0.0,artist|love|ship|titanic|wet,http://www.imdb.com/title/tt0120338/?ref_=fn_t...,USA,PG-13,14000.0,2.35
50,Baz Luhrmann,490.0,1.448128e+08,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912.0,753.0,English,105000000.0,...,29000.0,29770.0,Steve Bisley,4.0,ingratitude|mansion|party|title appears in wri...,http://www.imdb.com/title/tt1343092/?ref_=fn_t...,Australia,PG-13,509.0,2.35
97,Christopher Nolan,642.0,2.925689e+08,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200.0,2803.0,English,160000000.0,...,29000.0,81115.0,Joseph Gordon-Levitt,0.0,ambiguous ending|corporate espionage|dream|sub...,http://www.imdb.com/title/tt1375666/?ref_=fn_t...,USA,PG-13,27000.0,2.35
179,Alejandro G. Iñárritu,556.0,1.836359e+08,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020.0,1188.0,English,135000000.0,...,29000.0,57108.0,Lukas Haas,0.0,bear attack|cauterizing a wound|native america...,http://www.imdb.com/title/tt1663202/?ref_=fn_t...,USA,R,27000.0,2.35
257,Martin Scorsese,267.0,1.026088e+08,Biography|Drama,Leonardo DiCaprio,The Aviator,264318.0,799.0,English,110000000.0,...,29000.0,34582.0,Frances Conroy,0.0,1920s|aviation|fight|spruce goose|test flight,http://www.imdb.com/title/tt0338751/?ref_=fn_t...,USA,PG-13,3000.0,2.35
296,Quentin Tarantino,765.0,1.628046e+08,Drama|Western,Leonardo DiCaprio,Django Unchained,955174.0,1193.0,English,100000000.0,...,29000.0,40978.0,Ato Essandoh,1.0,dynamite|historically inaccurate|ku klux klan|...,http://www.imdb.com/title/tt1853728/?ref_=fn_t...,USA,R,11000.0,2.35
307,Edward Zwick,166.0,5.736626e+07,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292.0,657.0,English,100000000.0,...,29000.0,33160.0,Stephen Collins,0.0,diamond|elephant|fisherman|rebel|sierra leone,http://www.imdb.com/title/tt0450259/?ref_=fn_t...,Germany,R,3000.0,2.35
308,Martin Scorsese,606.0,1.168667e+08,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588.0,1138.0,English,100000000.0,...,29000.0,46057.0,Jon Favreau,3.0,based on true story|fellatio|female rear nudit...,http://www.imdb.com/title/tt0993846/?ref_=fn_t...,USA,R,11000.0,2.35
326,Martin Scorsese,233.0,7.767964e+07,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033.0,1166.0,English,100000000.0,...,29000.0,47657.0,Jim Broadbent,3.0,butcher|civil war|gangster|new york city|revenge,http://www.imdb.com/title/tt0217505/?ref_=fn_t...,USA,R,14000.0,2.35
361,Martin Scorsese,352.0,1.323734e+08,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649.0,2054.0,English,90000000.0,...,29000.0,45648.0,Ray Winstone,0.0,boston|mole|police|undercover|undercover cop,http://www.imdb.com/title/tt0407887/?ref_=fn_t...,USA,R,13000.0,2.35
452,Martin Scorsese,490.0,1.279684e+08,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092.0,964.0,English,80000000.0,...,29000.0,29585.0,Nellie Sciutto,0.0,female prisoner|plot twist|self delusion|surpr...,http://www.imdb.com/title/tt1130884/?ref_=fn_t...,USA,R,223.0,2.35
641,Ridley Scott,238.0,3.938044e+07,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248.0,263.0,English,70000000.0,...,29000.0,29824.0,Michael Gaston,1.0,cia|jordan|middle east|spy|terrorist,http://www.imdb.com/title/tt0758774/?ref_=fn_t...,USA,R,149.0,2.35
911,Steven Spielberg,194.0,1.644352e+08,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801.0,667.0,English,52000000.0,...,29000.0,48153.0,Jennifer Garner,0.0,attorney|cat and mouse|fbi|pan am|pilot,http://www.imdb.com/title/tt0264464/?ref_=fn_t...,USA,PG-13,15000.0,1.85
990,Danny Boyle,118.0,3.977860e+07,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169.0,548.0,English,50000000.0,...,29000.0,29461.0,Peter Youngblood Hills,0.0,love|map|paradise|thailand|travel,http://www.imdb.com/title/tt0163978/?ref_=fn_t...,USA,R,414.0,2.35
1114,Sam Mendes,323.0,2.287781e+07,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591.0,414.0,English,35000000.0,...,29000.0,53895.0,Joe Komara,0.0,based on novel|children|connecticut|suburb|work,http://www.imdb.com/title/tt0959337/?ref_=fn_t...,USA,R,14000.0,2.35
1422,Randall Wallace,83.0,5.687636e+07,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219.0,244.0,English,35000000.0,...,29000.0,29265.0,Judith Godrèche,1.0,france|musketeer|three musketeers|twin|twin br...,http://www.imdb.com/title/tt0120744/?ref_=fn_t...,USA,PG-13,130.0,1.85
1453,Clint Eastwood,392.0,3.730495e+07,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728.0,279.0,English,35000000.0,...,29000.0,36258.0,Kaitlyn Dever,0.0,agent|fbi|federal bureau of investigation|gay ...,http://www.imdb.com/title/tt1616195/?ref_=fn_t...,USA,R,6000.0,2.35
1560,Sam Raimi,63.0,1.863654e+07,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197.0,216.0,English,32000000.0,...,29000.0,29743.0,Roberts Blossom,0.0,authority figure as villian|gun duel|saved fro...,http://www.imdb.com/title/tt0114214/?ref_=fn_t...,Japan,R,165.0,1.85
2067,Jerry Zaks,45.0,1.278251e+07,Drama,Leonardo DiCaprio,Marvin's Room,20163.0,71.0,English,23000000.0,...,29000.0,63194.0,Meryl Streep,2.0,house|leukemia|mental institution|nursing home...,http://www.imdb.com/title/tt0116999/?ref_=fn_t...,USA,PG-13,22000.0,1.85
2757,Baz Luhrmann,106.0,4.633873e+07,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750.0,506.0,English,14500000.0,...,29000.0,33791.0,Brian Dennehy,2.0,hawaiian shirt|love|shakespeare adaptation|sha...,http://www.imdb.com/title/tt0117509/?ref_=fn_t...,USA,PG-13,1000.0,2.35
3476,Baz Luhrmann,490.0,1.448128e+08,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933.0,753.0,English,105000000.0,...,29000.0,29769.0,Steve Bisley,4.0,ingratitude|mansion|party|title appears in wri...,http://www.imdb.com/title/tt1343092/?ref_=fn_t...,Australia,PG-13,509.0,2.35
101,David Fincher,362.0,1.274908e+08,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346.0,822.0,English,150000000.0,...,11000.0,13333.0,Julia Ormond,2.0,deformed baby|diary|lingerie slip|older man yo...,http://www.imdb.com/title/tt0421715/?ref_=fn_t...,USA,PG-13,1000.0,2.35
147,Wolfgang Petersen,220.0,1.332283e+08,Adventure,Brad Pitt,Troy,381672.0,1694.0,English,175000000.0,...,11000.0,17944.0,Julian Glover,2.0,greek|mythology|prince|trojan|troy,http://www.imdb.com/title/tt0332452/?ref_=fn_t...,USA,R,5000.0,2.35
254,Steven Soderbergh,198.0,1.255316e+08,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852.0,627.0,English,110000000.0,...,11000.0,19359.0,Mini Anden,0.0,father daughter relationship|heist|pretending ...,http://www.imdb.com/title/tt0349903/?ref_=fn_t...,USA,PG-13,8000.0,2.35
255,Doug Liman,233.0,1.863361e+08,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861.0,798.0,English,120000000.0,...,11000.0,22722.0,Stephanie March,2.0,assassin|marriage|secret agent|suburb|target,http://www.imdb.com/title/tt0356910/?ref_=fn_t...,USA,PG-13,11000.0,2.35
382,Tony Scott,142.0,2.687100e+04,Action|Crime|Thriller,Brad Pitt,Spy Game,121259.0,361.0,English,92000000.0,...,11000.0,12499.0,Catherine McCormack,2.0,china|cia|cold war|friendship|retirement,http://www.imdb.com/title/tt0266987/?ref_=fn_t...,Germany,R,577.0,2.35
400,Steven Soderbergh,186.0,1.834058e+08,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645.0,845.0,English,85000000.0,...,11000.0,13028.0,Elliott Gould,4.0,card dealer|casino|criminal mastermind|recruit...,http://www.imdb.com/title/tt0240772/?ref_=fn_t...,USA,PG-13,1000.0,2.35
470,David Ayer,406.0,8.570712e+07,Action|Drama|War,Brad Pitt,Fury,303185.0,701.0,English,68000000.0,...,11000.0,20411.0,Jim Parrack,4.0,battle|battlefield|brutality|combat|tank,http://www.imdb.com/title/tt2713180/?ref_=fn_t...,USA,R,8000.0,2.35
611,Jean-Jacques Annaud,76.0,3.790151e+07,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385.0,119.0,English,70000000.0,...,11000.0,12226.0,Victor Wong,1.0,austria|dalai lama|himalaya|mountain|tibet,http://www.imdb.com/title/tt0120102/?ref_=fn_t...,USA,PG-13,691.0,2.35
683,David Fincher,315.0,3.702340e+07,Drama,Brad Pitt,Fight Club,1347461.0,2968.0,English,63000000.0,...,11000.0,13209.0,Eugenie Bondurant,2.0,anti establishment|dark humor|fighting|multipl...,http://www.imdb.com/title/tt0137523/?ref_=fn_t...,USA,R,783.0,2.35
792,Patrick Gilmore,98.0,2.628832e+07,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144.0,91.0,English,60000000.0,...,11000.0,11301.0,Timothy West,0.0,book|framed|goddess|prince|sinbad,http://www.imdb.com/title/tt0165982/?ref_=fn_t...,USA,PG,102.0,1.66
940,Neil Jordan,120.0,1.052646e+08,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752.0,406.0,English,60000000.0,...,11000.0,25697.0,Kirsten Dunst,0.0,betrayal|dangerous friend|gothic|monster as vi...,http://www.imdb.com/title/tt0110148/?ref_=fn_t...,USA,R,10000.0,1.85
1490,Terrence Malick,584.0,1.330332e+07,Drama|Fantasy,Brad Pitt,The Tree of Life,136367.0,975.0,English,32000000.0,...,11000.0,13021.0,Fiona Shaw,0.0,1950s|children|ice cube|texas|waco texas,http://www.imdb.com/title/tt0478304/?ref_=fn_t...,USA,PG-13,1000.0,1.85
1722,Andrew Dominik,273.0,3.904982e+06,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104.0,415.0,English,30000000.0,...,11000.0,22516.0,Sam Shepard,0.0,long title|outlaw|robbery|train|train robbery,http://www.imdb.com/title/tt0443680/?ref_=fn_t...,USA,R,10000.0,2.35
2204,Alejandro G. Iñárritu,285.0,3.430077e+07,Drama,Brad Pitt,Babel,243799.0,908.0,English,25000000.0,...,11000.0,11248.0,Dermot Crowley,3.0,american|destiny|mexican border|multiple persp...,http://www.imdb.com/title/tt0449467/?ref_=fn_t...,France,R,119.0,1.85
2333,Angelina Jolie Pitt,131.0,5.310090e+05,Drama|Romance,Brad Pitt,By the Sea,7976.0,61.0,English,10000000.0,...,11000.0,22319.0,Melvil Poupaud,0.0,cheating wife|cigarette smoking|male in shower...,http://www.imdb.com/title/tt3707106/?ref_=fn_t...,USA,R,11000.0,2.35
2682,Andrew Dominik,414.0,1.493857e+07,Crime|Thriller,Brad Pitt,Killing Them Softly,111625.0,369.0,English,15000000.0,...,11000.0,14025.0,Ben Mendelsohn,1.0,exploding car|hit by a car|poker game|punched ...,http://www.imdb.com/title/tt1764234/?ref_=fn_t...,USA,R,820.0,2.35
2898,Tony Scott,122.0,1.228150e+07,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492.0,460.0,English,13000000.0,...,11000.0,23602.0,Michael Rapaport,3.0,aspiring actor|cocaine|drugs|pimp|suitcase ful...,http://www.imdb.com/title/tt0108399/?ref_=fn_t...,USA,R,10000.0,2.35
4749,Tom DiCillo,10.0,NaN,Comedy|Music|Romance,Brad Pitt,Johnny Suede,3013.0,24.0,English,500000.0,...,11000.0,11839.0,Nick Cave,0.0,idol|musician|vomiting|watching television|wyo...,http://www.imdb.com/title/tt0104567/?ref_=fn_t...,Switzerland,R,422.0,1.85

In [29]:
# Write your code for grouping the combined dataframe here
Combined=Combined.groupby('actor_1_name')
Combined

In [30]:
# Write the code for finding the mean of critic reviews and audience reviews here
Combined=Combined[['num_critic_for_reviews','num_user_for_reviews']].mean().sort_values(['num_critic_for_reviews','num_user_for_reviews'],ascending=False)
Combined

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476            914.476190
Brad Pitt                      231.944444            702.444444
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!